/*
 * File:           C:\Users\PaulH\Documents\Arduino\AudioAmplifierADAU1701\SigmaStudio_project\Export\0_template_IC_1_PARAM.h
 *
 * Created:        Monday, December 23, 2024 2:07:57 PM
 * Description:    0_template:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2024 Analog Devices, Inc. All rights reserved.
 */
#ifndef __0_TEMPLATE_IC_1_PARAM_H__
#define __0_TEMPLATE_IC_1_PARAM_H__


/* Module DC1 - DC Input Entry*/
#define MOD_DC1_COUNT                                  1
#define MOD_DC1_DEVICE                                 "IC1"
#define MOD_DC1_DCINPALG1_ADDR                         0
#define MOD_DC1_DCINPALG1_FIXPT                        0xFDEADC0D
#define MOD_DC1_DCINPALG1_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-4.1651595831)
#define MOD_DC1_DCINPALG1_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module DC2 - DC Input Entry*/
#define MOD_DC2_COUNT                                  1
#define MOD_DC2_DEVICE                                 "IC1"
#define MOD_DC2_DCINPALG2_ADDR                         1
#define MOD_DC2_DCINPALG2_FIXPT                        0x00800000
#define MOD_DC2_DCINPALG2_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DC2_DCINPALG2_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter1 - General (2nd order)*/
#define MOD_GENFILTER1_COUNT                           5
#define MOD_GENFILTER1_DEVICE                          "IC1"
#define MOD_GENFILTER1_ALG0_STAGE0_B0_ADDR             2
#define MOD_GENFILTER1_ALG0_STAGE0_B0_FIXPT            0x007FDAE1
#define MOD_GENFILTER1_ALG0_STAGE0_B0_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998867231486796)
#define MOD_GENFILTER1_ALG0_STAGE0_B0_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_B1_ADDR             3
#define MOD_GENFILTER1_ALG0_STAGE0_B1_FIXPT            0xFF004A3D
#define MOD_GENFILTER1_ALG0_STAGE0_B1_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.99773446297359)
#define MOD_GENFILTER1_ALG0_STAGE0_B1_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_B2_ADDR             4
#define MOD_GENFILTER1_ALG0_STAGE0_B2_FIXPT            0x007FDAE1
#define MOD_GENFILTER1_ALG0_STAGE0_B2_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998867231486796)
#define MOD_GENFILTER1_ALG0_STAGE0_B2_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_A1_ADDR             5
#define MOD_GENFILTER1_ALG0_STAGE0_A1_FIXPT            0x00FFB5BC
#define MOD_GENFILTER1_ALG0_STAGE0_A1_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99773360720734)
#define MOD_GENFILTER1_ALG0_STAGE0_A1_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_A2_ADDR             6
#define MOD_GENFILTER1_ALG0_STAGE0_A2_FIXPT            0xFF804A36
#define MOD_GENFILTER1_ALG0_STAGE0_A2_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.997735318739846)
#define MOD_GENFILTER1_ALG0_STAGE0_A2_TYPE             SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen 1st Order1 - General (1st order)*/
#define MOD_GEN1STORDER1_COUNT                         3
#define MOD_GEN1STORDER1_DEVICE                        "IC1"
#define MOD_GEN1STORDER1_ALG0_PARAMB00_ADDR            7
#define MOD_GEN1STORDER1_ALG0_PARAMB00_FIXPT           0x00000663
#define MOD_GEN1STORDER1_ALG0_PARAMB00_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000195005513531021)
#define MOD_GEN1STORDER1_ALG0_PARAMB00_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GEN1STORDER1_ALG0_PARAMB10_ADDR            8
#define MOD_GEN1STORDER1_ALG0_PARAMB10_FIXPT           0x00000000
#define MOD_GEN1STORDER1_ALG0_PARAMB10_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_GEN1STORDER1_ALG0_PARAMB10_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GEN1STORDER1_ALG0_PARAMA00_ADDR            9
#define MOD_GEN1STORDER1_ALG0_PARAMA00_FIXPT           0x007FF99C
#define MOD_GEN1STORDER1_ALG0_PARAMA00_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.999804994486469)
#define MOD_GEN1STORDER1_ALG0_PARAMA00_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module SW vol 1 - Single slew ext vol*/
#define MOD_SWVOL1_COUNT                               1
#define MOD_SWVOL1_DEVICE                              "IC1"
#define MOD_SWVOL1_EXTSWGAINDB1STEP_ADDR               10
#define MOD_SWVOL1_EXTSWGAINDB1STEP_FIXPT              0x00000800
#define MOD_SWVOL1_EXTSWGAINDB1STEP_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL1_EXTSWGAINDB1STEP_TYPE               SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1_4 - Gain*/
#define MOD_GAIN1_4_COUNT                              1
#define MOD_GAIN1_4_DEVICE                             "IC1"
#define MOD_GAIN1_4_GAIN1940ALGNS4_ADDR                11
#define MOD_GAIN1_4_GAIN1940ALGNS4_FIXPT               0x01000000
#define MOD_GAIN1_4_GAIN1940ALGNS4_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_GAIN1_4_GAIN1940ALGNS4_TYPE                SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1_3 - Gain*/
#define MOD_GAIN1_3_COUNT                              1
#define MOD_GAIN1_3_DEVICE                             "IC1"
#define MOD_GAIN1_3_GAIN1940ALGNS3_ADDR                12
#define MOD_GAIN1_3_GAIN1940ALGNS3_FIXPT               0x01000000
#define MOD_GAIN1_3_GAIN1940ALGNS3_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2)
#define MOD_GAIN1_3_GAIN1940ALGNS3_TYPE                SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv2 - Running Average*/
#define MOD_AVGENV2_COUNT                              3
#define MOD_AVGENV2_DEVICE                             "IC1"
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_ADDR  13
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_FIXPT 0x0000096E
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_ADDR 14
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_FIXPT 0x00000000
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_ADDR 15
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_FIXPT 0x00000009
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1_2 - Gain*/
#define MOD_GAIN1_2_COUNT                              1
#define MOD_GAIN1_2_DEVICE                             "IC1"
#define MOD_GAIN1_2_GAIN1940ALGNS2_ADDR                16
#define MOD_GAIN1_2_GAIN1940ALGNS2_FIXPT               0x00400000
#define MOD_GAIN1_2_GAIN1940ALGNS2_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_GAIN1_2_GAIN1940ALGNS2_TYPE                SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv1 - Running Average*/
#define MOD_AVGENV1_COUNT                              3
#define MOD_AVGENV1_DEVICE                             "IC1"
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_ADDR  17
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_FIXPT 0x0000096E
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_ADDR 18
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_FIXPT 0x00000000
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_ADDR 19
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_FIXPT 0x00000009
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1 - Gain*/
#define MOD_GAIN1_COUNT                                1
#define MOD_GAIN1_DEVICE                               "IC1"
#define MOD_GAIN1_GAIN1940ALGNS1_ADDR                  20
#define MOD_GAIN1_GAIN1940ALGNS1_FIXPT                 0x00400000
#define MOD_GAIN1_GAIN1940ALGNS1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_GAIN1_GAIN1940ALGNS1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter2 - General (2nd order)*/
#define MOD_GENFILTER2_COUNT                           5
#define MOD_GENFILTER2_DEVICE                          "IC1"
#define MOD_GENFILTER2_ALG0_STAGE0_B0_ADDR             21
#define MOD_GENFILTER2_ALG0_STAGE0_B0_FIXPT            0x000043FF
#define MOD_GENFILTER2_ALG0_STAGE0_B0_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00207515404382363)
#define MOD_GENFILTER2_ALG0_STAGE0_B0_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_ALG0_STAGE0_B1_ADDR             22
#define MOD_GENFILTER2_ALG0_STAGE0_B1_FIXPT            0x00000000
#define MOD_GENFILTER2_ALG0_STAGE0_B1_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_GENFILTER2_ALG0_STAGE0_B1_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_ALG0_STAGE0_B2_ADDR             23
#define MOD_GENFILTER2_ALG0_STAGE0_B2_FIXPT            0xFFFFBC01
#define MOD_GENFILTER2_ALG0_STAGE0_B2_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.00207515404382363)
#define MOD_GENFILTER2_ALG0_STAGE0_B2_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_ALG0_STAGE0_A1_ADDR             24
#define MOD_GENFILTER2_ALG0_STAGE0_A1_FIXPT            0x00FF7774
#define MOD_GENFILTER2_ALG0_STAGE0_A1_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99583299352484)
#define MOD_GENFILTER2_ALG0_STAGE0_A1_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_ALG0_STAGE0_A2_ADDR             25
#define MOD_GENFILTER2_ALG0_STAGE0_A2_FIXPT            0xFF808800
#define MOD_GENFILTER2_ALG0_STAGE0_A2_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.995849691912353)
#define MOD_GENFILTER2_ALG0_STAGE0_A2_TYPE             SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter2_2 - General (2nd order)*/
#define MOD_GENFILTER2_2_COUNT                         5
#define MOD_GENFILTER2_2_DEVICE                        "IC1"
#define MOD_GENFILTER2_2_ALG0_STAGE0_B0_ADDR           26
#define MOD_GENFILTER2_2_ALG0_STAGE0_B0_FIXPT          0x00010E50
#define MOD_GENFILTER2_2_ALG0_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00824928753482917)
#define MOD_GENFILTER2_2_ALG0_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_2_ALG0_STAGE0_B1_ADDR           27
#define MOD_GENFILTER2_2_ALG0_STAGE0_B1_FIXPT          0x00000000
#define MOD_GENFILTER2_2_ALG0_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_GENFILTER2_2_ALG0_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_2_ALG0_STAGE0_B2_ADDR           28
#define MOD_GENFILTER2_2_ALG0_STAGE0_B2_FIXPT          0xFFFEF1B0
#define MOD_GENFILTER2_2_ALG0_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.00824928753482917)
#define MOD_GENFILTER2_2_ALG0_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_2_ALG0_STAGE0_A1_ADDR           29
#define MOD_GENFILTER2_2_ALG0_STAGE0_A1_FIXPT          0x00FDDAAC
#define MOD_GENFILTER2_2_ALG0_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98323590928321)
#define MOD_GENFILTER2_2_ALG0_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_2_ALG0_STAGE0_A2_ADDR           30
#define MOD_GENFILTER2_2_ALG0_STAGE0_A2_FIXPT          0xFF821CA1
#define MOD_GENFILTER2_2_ALG0_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.983501424930342)
#define MOD_GENFILTER2_2_ALG0_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter2_3 - General (2nd order)*/
#define MOD_GENFILTER2_3_COUNT                         5
#define MOD_GENFILTER2_3_DEVICE                        "IC1"
#define MOD_GENFILTER2_3_ALG0_STAGE0_B0_ADDR           31
#define MOD_GENFILTER2_3_ALG0_STAGE0_B0_FIXPT          0x00041F31
#define MOD_GENFILTER2_3_ALG0_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0322018984465262)
#define MOD_GENFILTER2_3_ALG0_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_3_ALG0_STAGE0_B1_ADDR           32
#define MOD_GENFILTER2_3_ALG0_STAGE0_B1_FIXPT          0x00000000
#define MOD_GENFILTER2_3_ALG0_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_GENFILTER2_3_ALG0_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_3_ALG0_STAGE0_B2_ADDR           33
#define MOD_GENFILTER2_3_ALG0_STAGE0_B2_FIXPT          0xFFFBE0CF
#define MOD_GENFILTER2_3_ALG0_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.0322018984465262)
#define MOD_GENFILTER2_3_ALG0_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_3_ALG0_STAGE0_A1_ADDR           34
#define MOD_GENFILTER2_3_ALG0_STAGE0_A1_FIXPT          0x00F739D1
#define MOD_GENFILTER2_3_ALG0_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.93145194305703)
#define MOD_GENFILTER2_3_ALG0_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_3_ALG0_STAGE0_A2_ADDR           35
#define MOD_GENFILTER2_3_ALG0_STAGE0_A2_FIXPT          0xFF883E63
#define MOD_GENFILTER2_3_ALG0_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.935596203106947)
#define MOD_GENFILTER2_3_ALG0_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter2_4 - General (2nd order)*/
#define MOD_GENFILTER2_4_COUNT                         5
#define MOD_GENFILTER2_4_DEVICE                        "IC1"
#define MOD_GENFILTER2_4_ALG0_STAGE0_B0_ADDR           36
#define MOD_GENFILTER2_4_ALG0_STAGE0_B0_FIXPT          0x000DB356
#define MOD_GENFILTER2_4_ALG0_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.107035414192852)
#define MOD_GENFILTER2_4_ALG0_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_4_ALG0_STAGE0_B1_ADDR           37
#define MOD_GENFILTER2_4_ALG0_STAGE0_B1_FIXPT          0x00000000
#define MOD_GENFILTER2_4_ALG0_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_GENFILTER2_4_ALG0_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_4_ALG0_STAGE0_B2_ADDR           38
#define MOD_GENFILTER2_4_ALG0_STAGE0_B2_FIXPT          0xFFF24CAA
#define MOD_GENFILTER2_4_ALG0_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.107035414192852)
#define MOD_GENFILTER2_4_ALG0_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_4_ALG0_STAGE0_A1_ADDR           39
#define MOD_GENFILTER2_4_ALG0_STAGE0_A1_FIXPT          0x00DE4860
#define MOD_GENFILTER2_4_ALG0_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.73658380643848)
#define MOD_GENFILTER2_4_ALG0_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_4_ALG0_STAGE0_A2_ADDR           40
#define MOD_GENFILTER2_4_ALG0_STAGE0_A2_FIXPT          0xFF9B66AD
#define MOD_GENFILTER2_4_ALG0_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.785929171614296)
#define MOD_GENFILTER2_4_ALG0_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter2_5 - General (2nd order)*/
#define MOD_GENFILTER2_5_COUNT                         5
#define MOD_GENFILTER2_5_DEVICE                        "IC1"
#define MOD_GENFILTER2_5_ALG0_STAGE0_B0_ADDR           41
#define MOD_GENFILTER2_5_ALG0_STAGE0_B0_FIXPT          0x0024C311
#define MOD_GENFILTER2_5_ALG0_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.287202971300262)
#define MOD_GENFILTER2_5_ALG0_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_5_ALG0_STAGE0_B1_ADDR           42
#define MOD_GENFILTER2_5_ALG0_STAGE0_B1_FIXPT          0x00000000
#define MOD_GENFILTER2_5_ALG0_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_GENFILTER2_5_ALG0_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_5_ALG0_STAGE0_B2_ADDR           43
#define MOD_GENFILTER2_5_ALG0_STAGE0_B2_FIXPT          0xFFDB3CEF
#define MOD_GENFILTER2_5_ALG0_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.287202971300262)
#define MOD_GENFILTER2_5_ALG0_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_5_ALG0_STAGE0_A1_ADDR           44
#define MOD_GENFILTER2_5_ALG0_STAGE0_A1_FIXPT          0x008107B1
#define MOD_GENFILTER2_5_ALG0_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.00804722520641)
#define MOD_GENFILTER2_5_ALG0_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER2_5_ALG0_STAGE0_A2_ADDR           45
#define MOD_GENFILTER2_5_ALG0_STAGE0_A2_FIXPT          0xFFC98623
#define MOD_GENFILTER2_5_ALG0_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.425594057399476)
#define MOD_GENFILTER2_5_ALG0_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv2_2 - Running Average*/
#define MOD_AVGENV2_2_COUNT                            3
#define MOD_AVGENV2_2_DEVICE                           "IC1"
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3RMS_ADDR 46
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3RMS_FIXPT 0x0000096E
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3RMS_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3HOLD_ADDR 47
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3HOLD_FIXPT 0x00000000
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3DECAY_ADDR 48
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3DECAY_FIXPT 0x00000009
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV2_2_ALG0_MONORUNAVGDETECTALG3DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv2_3 - Running Average*/
#define MOD_AVGENV2_3_COUNT                            3
#define MOD_AVGENV2_3_DEVICE                           "IC1"
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4RMS_ADDR 49
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4RMS_FIXPT 0x0000096E
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4RMS_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4HOLD_ADDR 50
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4HOLD_FIXPT 0x00000000
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4DECAY_ADDR 51
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4DECAY_FIXPT 0x00000009
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV2_3_ALG0_MONORUNAVGDETECTALG4DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv2_4 - Running Average*/
#define MOD_AVGENV2_4_COUNT                            3
#define MOD_AVGENV2_4_DEVICE                           "IC1"
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5RMS_ADDR 52
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5RMS_FIXPT 0x0000096E
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5RMS_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5HOLD_ADDR 53
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5HOLD_FIXPT 0x00000000
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5DECAY_ADDR 54
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5DECAY_FIXPT 0x00000009
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV2_4_ALG0_MONORUNAVGDETECTALG5DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv2_5 - Running Average*/
#define MOD_AVGENV2_5_COUNT                            3
#define MOD_AVGENV2_5_DEVICE                           "IC1"
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6RMS_ADDR 55
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6RMS_FIXPT 0x0000096E
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6RMS_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6HOLD_ADDR 56
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6HOLD_FIXPT 0x00000000
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6DECAY_ADDR 57
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6DECAY_FIXPT 0x00000009
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV2_5_ALG0_MONORUNAVGDETECTALG6DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv2_6 - Running Average*/
#define MOD_AVGENV2_6_COUNT                            3
#define MOD_AVGENV2_6_DEVICE                           "IC1"
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7RMS_ADDR 58
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7RMS_FIXPT 0x0000096E
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7RMS_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7HOLD_ADDR 59
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7HOLD_FIXPT 0x00000000
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7DECAY_ADDR 60
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7DECAY_FIXPT 0x00000009
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV2_6_ALG0_MONORUNAVGDETECTALG7DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module BAND0_RMS - DSP Readback*/
#define MOD_BAND0_RMS_COUNT                            2
#define MOD_BAND0_RMS_DEVICE                           "IC1"
#define MOD_BAND0_RMS_ALG0_VAL0_ADDR                   2074
#define MOD_BAND0_RMS_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x04F6)
#define MOD_BAND0_RMS_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_BAND0_RMS_ALG0_VAL0_READBACK_ADDR          0
#define MOD_BAND0_RMS_ALG0_VAL1_ADDR                   2074
#define MOD_BAND0_RMS_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_BAND0_RMS_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

/* Module VolumeADC - DSP Readback*/
#define MOD_VOLUMEADC_COUNT                            2
#define MOD_VOLUMEADC_DEVICE                           "IC1"
#define MOD_VOLUMEADC_ALG0_VAL0_ADDR                   2074
#define MOD_VOLUMEADC_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x00D6)
#define MOD_VOLUMEADC_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_VOLUMEADC_ALG0_VAL0_READBACK_ADDR          0
#define MOD_VOLUMEADC_ALG0_VAL1_ADDR                   2074
#define MOD_VOLUMEADC_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_VOLUMEADC_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

/* Module CH1_RMS - DSP Readback*/
#define MOD_CH1_RMS_COUNT                              2
#define MOD_CH1_RMS_DEVICE                             "IC1"
#define MOD_CH1_RMS_ALG0_VAL0_ADDR                     2074
#define MOD_CH1_RMS_ALG0_VAL0_VALUES                   SIGMASTUDIOTYPE_SPECIAL(0x022E)
#define MOD_CH1_RMS_ALG0_VAL0_TYPE                     SIGMASTUDIOTYPE_SPECIAL
#define MOD_CH1_RMS_ALG0_VAL0_READBACK_ADDR            0
#define MOD_CH1_RMS_ALG0_VAL1_ADDR                     2074
#define MOD_CH1_RMS_ALG0_VAL1_VALUE                    SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_CH1_RMS_ALG0_VAL1_TYPE                     SIGMASTUDIOTYPE_5_19

/* Module BalanceADC - DSP Readback*/
#define MOD_BALANCEADC_COUNT                           2
#define MOD_BALANCEADC_DEVICE                          "IC1"
#define MOD_BALANCEADC_ALG0_VAL0_ADDR                  2074
#define MOD_BALANCEADC_ALG0_VAL0_VALUES                SIGMASTUDIOTYPE_SPECIAL(0x0102)
#define MOD_BALANCEADC_ALG0_VAL0_TYPE                  SIGMASTUDIOTYPE_SPECIAL
#define MOD_BALANCEADC_ALG0_VAL0_READBACK_ADDR         0
#define MOD_BALANCEADC_ALG0_VAL1_ADDR                  2074
#define MOD_BALANCEADC_ALG0_VAL1_VALUE                 SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_BALANCEADC_ALG0_VAL1_TYPE                  SIGMASTUDIOTYPE_5_19

/* Module ReadBack1 - DSP Readback*/
#define MOD_READBACK1_COUNT                            2
#define MOD_READBACK1_DEVICE                           "IC1"
#define MOD_READBACK1_ALG0_VAL0_ADDR                   2074
#define MOD_READBACK1_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x004A)
#define MOD_READBACK1_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_READBACK1_ALG0_VAL0_READBACK_ADDR          0
#define MOD_READBACK1_ALG0_VAL1_ADDR                   2074
#define MOD_READBACK1_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_READBACK1_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

/* Module BAND2_RMS - DSP Readback*/
#define MOD_BAND2_RMS_COUNT                            2
#define MOD_BAND2_RMS_DEVICE                           "IC1"
#define MOD_BAND2_RMS_ALG0_VAL0_ADDR                   2074
#define MOD_BAND2_RMS_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x050E)
#define MOD_BAND2_RMS_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_BAND2_RMS_ALG0_VAL0_READBACK_ADDR          0
#define MOD_BAND2_RMS_ALG0_VAL1_ADDR                   2074
#define MOD_BAND2_RMS_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_BAND2_RMS_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

/* Module BAND3_RMS - DSP Readback*/
#define MOD_BAND3_RMS_COUNT                            2
#define MOD_BAND3_RMS_DEVICE                           "IC1"
#define MOD_BAND3_RMS_ALG0_VAL0_ADDR                   2074
#define MOD_BAND3_RMS_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x051A)
#define MOD_BAND3_RMS_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_BAND3_RMS_ALG0_VAL0_READBACK_ADDR          0
#define MOD_BAND3_RMS_ALG0_VAL1_ADDR                   2074
#define MOD_BAND3_RMS_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_BAND3_RMS_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

/* Module BAND1_RMS - DSP Readback*/
#define MOD_BAND1_RMS_COUNT                            2
#define MOD_BAND1_RMS_DEVICE                           "IC1"
#define MOD_BAND1_RMS_ALG0_VAL0_ADDR                   2074
#define MOD_BAND1_RMS_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x0502)
#define MOD_BAND1_RMS_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_BAND1_RMS_ALG0_VAL0_READBACK_ADDR          0
#define MOD_BAND1_RMS_ALG0_VAL1_ADDR                   2074
#define MOD_BAND1_RMS_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_BAND1_RMS_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

/* Module CH0_RMS - DSP Readback*/
#define MOD_CH0_RMS_COUNT                              2
#define MOD_CH0_RMS_DEVICE                             "IC1"
#define MOD_CH0_RMS_ALG0_VAL0_ADDR                     2074
#define MOD_CH0_RMS_ALG0_VAL0_VALUES                   SIGMASTUDIOTYPE_SPECIAL(0x0256)
#define MOD_CH0_RMS_ALG0_VAL0_TYPE                     SIGMASTUDIOTYPE_SPECIAL
#define MOD_CH0_RMS_ALG0_VAL0_READBACK_ADDR            0
#define MOD_CH0_RMS_ALG0_VAL1_ADDR                     2074
#define MOD_CH0_RMS_ALG0_VAL1_VALUE                    SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_CH0_RMS_ALG0_VAL1_TYPE                     SIGMASTUDIOTYPE_5_19

/* Module BAND4_RMS - DSP Readback*/
#define MOD_BAND4_RMS_COUNT                            2
#define MOD_BAND4_RMS_DEVICE                           "IC1"
#define MOD_BAND4_RMS_ALG0_VAL0_ADDR                   2074
#define MOD_BAND4_RMS_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x0526)
#define MOD_BAND4_RMS_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_BAND4_RMS_ALG0_VAL0_READBACK_ADDR          0
#define MOD_BAND4_RMS_ALG0_VAL1_ADDR                   2074
#define MOD_BAND4_RMS_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_BAND4_RMS_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

#endif
