/*
 * File:           C:\Users\PaulH\Documents\Arduino\AudioAmplifierADAU1701\SigmaStudio_project\Export\0_template_IC_1_PARAM.h
 *
 * Created:        Sunday, December 22, 2024 4:16:02 PM
 * Description:    0_template:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2024 Analog Devices, Inc. All rights reserved.
 */
#ifndef __0_TEMPLATE_IC_1_PARAM_H__
#define __0_TEMPLATE_IC_1_PARAM_H__


/* Module DC1 - DC Input Entry*/
#define MOD_DC1_COUNT                                  1
#define MOD_DC1_DEVICE                                 "IC1"
#define MOD_DC1_DCINPALG1_ADDR                         0
#define MOD_DC1_DCINPALG1_FIXPT                        0xFDEADC0D
#define MOD_DC1_DCINPALG1_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-4.1651595831)
#define MOD_DC1_DCINPALG1_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter1 - General (2nd order)*/
#define MOD_GENFILTER1_COUNT                           5
#define MOD_GENFILTER1_DEVICE                          "IC1"
#define MOD_GENFILTER1_ALG0_STAGE0_B0_ADDR             1
#define MOD_GENFILTER1_ALG0_STAGE0_B0_FIXPT            0x007FDAE1
#define MOD_GENFILTER1_ALG0_STAGE0_B0_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998867231486796)
#define MOD_GENFILTER1_ALG0_STAGE0_B0_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_B1_ADDR             2
#define MOD_GENFILTER1_ALG0_STAGE0_B1_FIXPT            0xFF004A3D
#define MOD_GENFILTER1_ALG0_STAGE0_B1_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.99773446297359)
#define MOD_GENFILTER1_ALG0_STAGE0_B1_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_B2_ADDR             3
#define MOD_GENFILTER1_ALG0_STAGE0_B2_FIXPT            0x007FDAE1
#define MOD_GENFILTER1_ALG0_STAGE0_B2_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.998867231486796)
#define MOD_GENFILTER1_ALG0_STAGE0_B2_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_A1_ADDR             4
#define MOD_GENFILTER1_ALG0_STAGE0_A1_FIXPT            0x00FFB5BC
#define MOD_GENFILTER1_ALG0_STAGE0_A1_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.99773360720734)
#define MOD_GENFILTER1_ALG0_STAGE0_A1_TYPE             SIGMASTUDIOTYPE_FIXPOINT
#define MOD_GENFILTER1_ALG0_STAGE0_A2_ADDR             5
#define MOD_GENFILTER1_ALG0_STAGE0_A2_FIXPT            0xFF804A36
#define MOD_GENFILTER1_ALG0_STAGE0_A2_VALUE            SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.997735318739846)
#define MOD_GENFILTER1_ALG0_STAGE0_A2_TYPE             SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv1 - Running Average*/
#define MOD_AVGENV1_COUNT                              3
#define MOD_AVGENV1_DEVICE                             "IC1"
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_ADDR  6
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_FIXPT 0x0000096E
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_ADDR 7
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_FIXPT 0x00000000
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_ADDR 8
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_FIXPT 0x00000009
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv2 - Running Average*/
#define MOD_AVGENV2_COUNT                              3
#define MOD_AVGENV2_DEVICE                             "IC1"
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_ADDR  9
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_FIXPT 0x0000096E
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000287864561677509)
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2RMS_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_ADDR 10
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_FIXPT 0x00000000
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_ADDR 11
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_FIXPT 0x00000009
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.08506944444444E-06)
#define MOD_AVGENV2_ALG0_MONORUNAVGDETECTALG2DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module CH0_RMS - DSP Readback*/
#define MOD_CH0_RMS_COUNT                              2
#define MOD_CH0_RMS_DEVICE                             "IC1"
#define MOD_CH0_RMS_ALG0_VAL0_ADDR                     2074
#define MOD_CH0_RMS_ALG0_VAL0_VALUES                   SIGMASTUDIOTYPE_SPECIAL(0x0156)
#define MOD_CH0_RMS_ALG0_VAL0_TYPE                     SIGMASTUDIOTYPE_SPECIAL
#define MOD_CH0_RMS_ALG0_VAL0_READBACK_ADDR            0
#define MOD_CH0_RMS_ALG0_VAL1_ADDR                     2074
#define MOD_CH0_RMS_ALG0_VAL1_VALUE                    SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_CH0_RMS_ALG0_VAL1_TYPE                     SIGMASTUDIOTYPE_5_19

/* Module CH1_RMS - DSP Readback*/
#define MOD_CH1_RMS_COUNT                              2
#define MOD_CH1_RMS_DEVICE                             "IC1"
#define MOD_CH1_RMS_ALG0_VAL0_ADDR                     2074
#define MOD_CH1_RMS_ALG0_VAL0_VALUES                   SIGMASTUDIOTYPE_SPECIAL(0x0162)
#define MOD_CH1_RMS_ALG0_VAL0_TYPE                     SIGMASTUDIOTYPE_SPECIAL
#define MOD_CH1_RMS_ALG0_VAL0_READBACK_ADDR            0
#define MOD_CH1_RMS_ALG0_VAL1_ADDR                     2074
#define MOD_CH1_RMS_ALG0_VAL1_VALUE                    SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_CH1_RMS_ALG0_VAL1_TYPE                     SIGMASTUDIOTYPE_5_19

/* Module ReadBack1 - DSP Readback*/
#define MOD_READBACK1_COUNT                            2
#define MOD_READBACK1_DEVICE                           "IC1"
#define MOD_READBACK1_ALG0_VAL0_ADDR                   2074
#define MOD_READBACK1_ALG0_VAL0_VALUES                 SIGMASTUDIOTYPE_SPECIAL(0x0032)
#define MOD_READBACK1_ALG0_VAL0_TYPE                   SIGMASTUDIOTYPE_SPECIAL
#define MOD_READBACK1_ALG0_VAL0_READBACK_ADDR          0
#define MOD_READBACK1_ALG0_VAL1_ADDR                   2074
#define MOD_READBACK1_ALG0_VAL1_VALUE                  SIGMASTUDIOTYPE_5_19_CONVERT(0)
#define MOD_READBACK1_ALG0_VAL1_TYPE                   SIGMASTUDIOTYPE_5_19

#endif
